-- Rollback Billing V1
DROP TABLE DH_BILLING_AUDIT PURGE;
DROP TABLE DH_PAYMENT_EVENTS PURGE;
DROP TABLE DH_BILLING_INVOICES PURGE;
DROP TABLE DH_SUBSCRIPTIONS PURGE;
DROP TABLE DH_BILLING_ACCOUNTS PURGE;
DROP TABLE DH_BILLING_POLICIES PURGE;
